apiVersion: v2
name: seldon-operator
description: Seldon Core Operator pinned to amd64 control-plane
type: application
version: 0.1.0
dependencies:
  - name: seldon-core-operator
    version: "1.17.x"
    repository: "https://storage.googleapis.com/seldon-charts"
