apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    export let options = {
      stages: [
        { duration: '2m', target: 10 },
        { duration: '10m', target: 30 },
        { duration: '8m', target: 60 },
        { duration: '5m', target: 10 }
      ]
    };
    const URL = __ENV.URL || 'http://rul-fastapi.mlops-edge/api/v1.0/predict';
    export default function () {
      http.get(URL);
      sleep(0.1);
    }
