apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-{{ .Values.service.name }}
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  namespaceSelector:
    matchNames: [ {{ .Release.Namespace | quote }} ]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
