apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  labels:
    release: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
