apiVersion: v2
name: redis-cloud
description: Bitnami Redis for core/cloud node (amd64)
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: "19.x.x"
    repository: "https://charts.bitnami.com/bitnami"
