
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mlflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mlflow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mlflow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://0.0.0.0:5000"
            - name: BACKEND_STORE_URI
              value: "{{ .Values.backendStore.uri }}"
            - name: ARTIFACT_ROOT
              value: "s3://{{ .Values.artifactStore.s3Bucket }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.artifactStore.accessKey }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.artifactStore.secretKey }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.artifactStore.region }}"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "{{ .Values.artifactStore.s3Endpoint }}"
          args:
            - "server"
            - "--backend-store-uri=$(BACKEND_STORE_URI)"
            - "--artifacts-destination=$(ARTIFACT_ROOT)"
            - "--host=0.0.0.0"
            - "--port=5000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
