apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector: { matchLabels: { app: mlflow } }
  template:
    metadata: { labels: { app: mlflow } }
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: mlflow
          image: {{ .Values.image }}
          env:
            - { name: MLFLOW_S3_ENDPOINT_URL, value: {{ .Values.s3.endpoint | quote }} }
            - { name: AWS_ACCESS_KEY_ID, value: {{ .Values.s3.accessKey | quote }} }
            - { name: AWS_SECRET_ACCESS_KEY, value: {{ .Values.s3.secretKey | quote }} }
          command: ["mlflow","server",
                    "--backend-store-uri","sqlite:////mlflow/mlflow.db",
                    "--default-artifact-root","s3://{{ .Values.s3.bucket }}/",
                    "--host","0.0.0.0","--port","5000"]
          ports: [ { name: http, containerPort: 5000 } ]
          volumeMounts: [ { name: data, mountPath: /mlflow } ]
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: mlflow-pvc }
