apiVersion: batch/v1
kind: Job
metadata: { name: minio-make-bucket }
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:RELEASE.2024-09-30T16-20-04Z
          env:
            - name: MC_HOST_myminio
              value: http://$(MINIO_ACCESS):$(MINIO_SECRET)@minio:9000
            - name: MINIO_ACCESS
              valueFrom: { secretKeyRef: { name: minio-creds, key: accesskey } }
            - name: MINIO_SECRET
              valueFrom: { secretKeyRef: { name: minio-creds, key: secretkey } }
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio http://minio:9000 $(MINIO_ACCESS) $(MINIO_SECRET)
              mc mb --ignore-existing myminio/{{ .Values.bucket }}
