
grafana:
  adminUser: admin
  adminPassword: admin123
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - grafana.local
    path: /
    pathType: Prefix
    tls: []
prometheus:
  ingress:
    enabled: false
alertmanager:
  enabled: true
  ingress:
    enabled: false
