apiVersion: v1
kind: ConfigMap
metadata: { name: trainer-script }
data:
  train.py: |
    import os, mlflow, mlflow.sklearn
    from sklearn.linear_model import LinearRegression
    from sklearn.datasets import make_regression
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import mean_absolute_error
    import joblib, numpy as np

    mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
    mlflow.set_experiment(os.environ.get("EXPERIMENT","rul-demo"))

    X, y = make_regression(n_samples=2000, n_features=4, noise=7.0, random_state=42)
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42)
    with mlflow.start_run() as run:
        model = LinearRegression().fit(Xtr, ytr)
        pred = model.predict(Xte)
        mae = mean_absolute_error(yte, pred)
        mlflow.log_metric("mae", mae)
        mlflow.sklearn.log_model(model, "model")

        out = "/output/model.joblib"
        joblib.dump(model, out)
        print("Saved", out)
