apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    export let options = {
      stages: {{ toJson .Values.stages }}
    };
    const URL = __ENV.URL || '{{ .Values.targetUrl }}';
    export default function () {
      http.get(URL);
      sleep(0.1);
    }
