apiVersion: batch/v1
kind: Job
metadata:
  name: k6-loadtest
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: {{ .Values.image }}
          command: ["k6", "run", "/scripts/test.js"]
          env:
            - name: URL
              value: "{{ .Values.targetUrl }}"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: k6-script
