apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k6-loadtest
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: k6
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
